### ISSUE TITLE
微信支付没有Demo

### ISSUE THREAD

**Issue by jerry-sl** [cloudorz/Diplomat#11]
DiplomatProxyProtocol中实现了一个pay方法  但是没有demo  也没有文档

**Comment by cloudorz** [comment]
下面是微信支付过程 Swift 

```
if let proxy = Diplomat.sharedInstance().proxyForName(kDiplomatTypeWechat) as? WechatProxy
{
 // TODO: 从服务器获取订单信息 order 。 注：将返回订单信息数据适配 Protocol DTWechatPaymentOrder

  proxy.pay(order) { (result, error) in
    // TODO: 成功后从服务器查询购买完成的订单信息。
  }
}
```

微信支付的重点是服务端生成订单签名。

微信支付 [业务流程](https://pay.weixin.qq.com/wiki/doc/api/app.php?chapter=8_3) [API 端的步骤](https://pay.weixin.qq.com/wiki/doc/api/app.php?chapter=8_5)

Demo 参见官方 [SDK](https://pay.weixin.qq.com/wiki/doc/api/app.php?chapter=11_1) 支付相关部分。
