### ISSUE TITLE
苹果审核被拒-10.6 

### ISSUE THREAD

**Issue by EnjoySR** [cloudorz/Diplomat#12]
一个哥们反映回来的，详细信息如下：
We noticed an issue in your app that contributes to a lower quality user experience than Apple users expect: 
- Upon tapping the button to share app content via QQ and QQ Zone, a web page in mobile Safari opens for logging in, then returns the user to the app. The user should be able to use the share feature without opening Safari.

Next Steps

It would be appropriate to revise your app to address all instances of this type of issue.

**Comment by cloudorz** [comment]
因为审核的人没有安装 QQ 客户端，并且开发中使用了 QZone 分享的模式，这样分享到 QZone 会跳转到 Safari 进行。
建议：
1. QZone 通过 QQ 客户端来分享。
2. 通过 `isInstalled:` 来判断是否安装 QQ 或 Wechat 客户端来是否显示相应的入口。（注意 iOS 9 上的设置）
