### ISSUE TITLE
Swift 中使用,导入头文件报下面的错误

### ISSUE THREAD

**Issue by shiios** [cloudorz/Diplomat#13]
No such module "WeiboProxy"

**Comment by cloudorz** [comment]
@shiios 
我看下你的 Podfile 中是怎么加入 Diplomat 的？还有 Bridging 中 import 的条目

**Comment by shiios** [comment]
已经解决啊!谢谢你的负责态度.我的问题属于pod时除了问题.

**Comment by cloudorz** [comment]
@shiios   👍
