### ISSUE TITLE
swift版本问题

### ISSUE THREAD

**Issue by xiaoxidong** [cloudorz/Diplomat#4]
你好，我在swift里面使用Diplomat，但是在userInfo里面的Dictionary为NSObject: AnyObject,但是message.userInfo = [kWechatSceneTypeKey: WXSceneSession]，这个会提示kWechatSceneTypeKey使String，麻烦问下这个问题应该要怎么解决？十分感谢~

**Comment by cloudorz** [comment]
Swift 中这个地方的确有些蛋疼。
可以这么写：
`message.userInfo = [kWechatSceneTypeKey: (Int)(WXSceneSession.value)]`

**Comment by xiaoxidong** [comment]
十分感谢~

**Comment by shiios** [comment]
swift 当中导入Diplomat头文件时,找不到怎回事?请问怎么解决才好?

**Comment by cloudorz** [comment]
@shiios 这个问题和你开的  #13 是同一个？
