### ISSUE TITLE
微博登录不成功

### ISSUE THREAD

**Issue by sinofake** [cloudorz/Diplomat#6]
应该是微博AppIdKey和Demo的bundle identifier不匹配
![image](https://cloud.githubusercontent.com/assets/6140191/8634692/93bd9b92-2835-11e5-8b97-b16b73fb8e56.png)

**Comment by cloudorz** [comment]
这个将 demo 的 bundle identifier 改成和微博的 SDK 的一致，应该可以解决。
我会将 Diplomat demo 的 bundle identifier 换下。
