### ISSUE TITLE
在userinfo中选择发送到QQ空间，成功跳转到QQ客户端，但是背景没有push进入好友动态列表，而是选择对话列表。

### ISSUE THREAD

**Issue by KittenYang** [cloudorz/Diplomat#7]
我留意了官方分享库的做法，如果是分享到QQ空间，跳转到QQ客户端的时候会自动push进入好友动态列表。

**Comment by cloudorz** [comment]
`message.userInfo = @{kTencentQQSceneTypeKey: @(TencentSceneZone)}`
在安装 QQ 客户端的情况下，会跳转到 好友动态 。 在没有安装 QQ 客户端的情况下跳转到 Safari 浏览器。
但分享的内容是纯文本或图片会调整到 TencentSceneQQ 模式，并设置 `cflag = kQQAPICtrlFlagQZoneShareOnStart` 来分享到 QZone 。如果不这样处理，会有成功分享到 好友动态 后无法返回到原应用的 bug 。

**Comment by sinofake** [comment]
之前分享多媒体内容到QZone，发送成功后不能返回是因为错误的调用了

``` objective-c
apiObject.cflag = kQQAPICtrlFlagQQShare;
 status = [QQApiInterface SendReqToQZone:request];
```

去掉这句代码

``` objective-c
apiObject.cflag = kQQAPICtrlFlagQQShare;
```

就会在分享成功后弹出 是留在QQ 还是返回原应用的对话框
