### ISSUE TITLE
Demo无法编译

### ISSUE THREAD

**Issue by tuchangwei** [cloudorz/Diplomat#9]
Demo无法编译

**Comment by sinofake** [comment]
![736f4ac7-ab3c-4b29-ac83-5fe98162dbe4](https://cloud.githubusercontent.com/assets/6140191/9897098/28c4c9d4-5c77-11e5-8c83-6928502dffaa.png)
删除TARGETS中的DiplomatTests即可运行

**Comment by cloudorz** [comment]
如果是 DiplomatTests 导致编译错误，原因是 DiplomatTests -> General -> Host Application 的配置不正确。
已作调整。
